spring.application.name=commission-backend

server.port=8080

spring.r2dbc.url=r2dbc:h2:mem:///commissionsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=commission_user
spring.r2dbc.password=commission_pwd
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.org.springframework.r2dbc=INFO
